### ISSUE TITLE
CA Certs broken in 0.0.19

### ISSUE THREAD

**Issue by kolsys** [iamtelescope/telescope#50]
After migrate to 0.0.19 got error 
```
HttpClient.__init__() got an unexpected keyword argument 'ca_certs'
```

### How to reproduce

- Create new connection 
- Select Use SSL
- Select Verify
- Define CA Certs property
- Press Validate button

### Temporary workaround

Clean up CA certs field and disable SSL Verify

**Comment by HumanUser** [comment]
Thanks for report. Will check it
